# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dm_alchemy/encode/chemistries.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dm_alchemy/encode/chemistries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dm_alchemy.encode import precomputed_maps_pb2 as dm__alchemy_dot_encode_dot_precomputed__maps__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#dm_alchemy/encode/chemistries.proto\x12\x07\x61lchemy\x1a(dm_alchemy/encode/precomputed_maps.proto\"n\n\tChemistry\x12\x12\n\npotion_map\x18\x01 \x01(\x05\x12\x11\n\tstone_map\x18\x02 \x01(\x05\x12(\n\x05graph\x18\x03 \x01(\x0b\x32\x19.alchemy.GraphArray.Entry\x12\x10\n\x08rotation\x18\x04 \x03(\x02\"-\n\nTrialItems\x12\x0e\n\x06stones\x18\x01 \x03(\x05\x12\x0f\n\x07potions\x18\x02 \x03(\x05\"8\n\x0c\x45pisodeItems\x12(\n\x0btrial_items\x18\x01 \x03(\x0b\x32\x13.alchemy.TrialItems\"`\n\x11\x43hemistryAndItems\x12%\n\tchemistry\x18\x01 \x01(\x0b\x32\x12.alchemy.Chemistry\x12$\n\x05items\x18\x02 \x01(\x0b\x32\x15.alchemy.EpisodeItems\"F\n\x13\x43hemistriesAndItems\x12/\n\x0b\x63hemistries\x18\x01 \x03(\x0b\x32\x1a.alchemy.ChemistryAndItemsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dm_alchemy.encode.chemistries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHEMISTRY']._serialized_start=90
  _globals['_CHEMISTRY']._serialized_end=200
  _globals['_TRIALITEMS']._serialized_start=202
  _globals['_TRIALITEMS']._serialized_end=247
  _globals['_EPISODEITEMS']._serialized_start=249
  _globals['_EPISODEITEMS']._serialized_end=305
  _globals['_CHEMISTRYANDITEMS']._serialized_start=307
  _globals['_CHEMISTRYANDITEMS']._serialized_end=403
  _globals['_CHEMISTRIESANDITEMS']._serialized_start=405
  _globals['_CHEMISTRIESANDITEMS']._serialized_end=475
# @@protoc_insertion_point(module_scope)
