# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dm_alchemy/encode/precomputed_maps.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dm_alchemy/encode/precomputed_maps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(dm_alchemy/encode/precomputed_maps.proto\x12\x07\x61lchemy\",\n\nFloatArray\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"*\n\x08IntArray\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\x05\x12\r\n\x05shape\x18\x02 \x03(\x05\"/\n\rBitfieldArray\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\"}\n\rListIntsArray\x12-\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1c.alchemy.ListIntsArray.Entry\x12\r\n\x05shape\x18\x02 \x03(\x05\x1a.\n\x05\x45ntry\x12\x14\n\x0clist_present\x18\x01 \x01(\x08\x12\x0f\n\x07\x65ntries\x18\x02 \x03(\x05\"f\n\nGraphArray\x12*\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x19.alchemy.GraphArray.Entry\x12\r\n\x05shape\x18\x02 \x03(\x05\x1a\x1d\n\x05\x45ntry\x12\x14\n\x0c\x65\x64ge_present\x18\x01 \x03(\x05\"\x9b\x01\n PartialGraphIndexToPossibleIndex\x12G\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x36.alchemy.PartialGraphIndexToPossibleIndex.EntriesEntry\x1a.\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x9b\x01\n\x12PossibleLatentDirs\x12\x32\n\x07\x65ntries\x18\x01 \x03(\x0b\x32!.alchemy.PossibleLatentDirs.Entry\x12\r\n\x05shape\x18\x02 \x03(\x05\x1a\x42\n\x05\x45ntry\x12\x1a\n\x12\x63ould_be_unchanged\x18\x01 \x01(\x08\x12\x1d\n\x15plausible_latent_dirs\x18\x02 \x03(\x05\"\x8a\x01\n\x16PartialPotionMapUpdate\x12\x36\n\x07\x65ntries\x18\x01 \x03(\x0b\x32%.alchemy.PartialPotionMapUpdate.Entry\x12\r\n\x05shape\x18\x02 \x03(\x05\x1a)\n\x05\x45ntry\x12\x0f\n\x07index_0\x18\x01 \x01(\x05\x12\x0f\n\x07index_1\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dm_alchemy.encode.precomputed_maps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARTIALGRAPHINDEXTOPOSSIBLEINDEX_ENTRIESENTRY']._loaded_options = None
  _globals['_PARTIALGRAPHINDEXTOPOSSIBLEINDEX_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_FLOATARRAY']._serialized_start=53
  _globals['_FLOATARRAY']._serialized_end=97
  _globals['_INTARRAY']._serialized_start=99
  _globals['_INTARRAY']._serialized_end=141
  _globals['_BITFIELDARRAY']._serialized_start=143
  _globals['_BITFIELDARRAY']._serialized_end=190
  _globals['_LISTINTSARRAY']._serialized_start=192
  _globals['_LISTINTSARRAY']._serialized_end=317
  _globals['_LISTINTSARRAY_ENTRY']._serialized_start=271
  _globals['_LISTINTSARRAY_ENTRY']._serialized_end=317
  _globals['_GRAPHARRAY']._serialized_start=319
  _globals['_GRAPHARRAY']._serialized_end=421
  _globals['_GRAPHARRAY_ENTRY']._serialized_start=392
  _globals['_GRAPHARRAY_ENTRY']._serialized_end=421
  _globals['_PARTIALGRAPHINDEXTOPOSSIBLEINDEX']._serialized_start=424
  _globals['_PARTIALGRAPHINDEXTOPOSSIBLEINDEX']._serialized_end=579
  _globals['_PARTIALGRAPHINDEXTOPOSSIBLEINDEX_ENTRIESENTRY']._serialized_start=533
  _globals['_PARTIALGRAPHINDEXTOPOSSIBLEINDEX_ENTRIESENTRY']._serialized_end=579
  _globals['_POSSIBLELATENTDIRS']._serialized_start=582
  _globals['_POSSIBLELATENTDIRS']._serialized_end=737
  _globals['_POSSIBLELATENTDIRS_ENTRY']._serialized_start=671
  _globals['_POSSIBLELATENTDIRS_ENTRY']._serialized_end=737
  _globals['_PARTIALPOTIONMAPUPDATE']._serialized_start=740
  _globals['_PARTIALPOTIONMAPUPDATE']._serialized_end=878
  _globals['_PARTIALPOTIONMAPUPDATE_ENTRY']._serialized_start=837
  _globals['_PARTIALPOTIONMAPUPDATE_ENTRY']._serialized_end=878
# @@protoc_insertion_point(module_scope)
