#!/usr/bin/env python3
"""
Analyze overlap between support and query examples from different seed files.
This script reads JSON files generated by support_and_query_generator.py for different seeds
and calculates the overlap in support and query examples.
"""

import json
import sys
import os
from typing import Set, List, Dict, Any

def load_json_file(file_path: str) -> Dict[str, Any]:
    """Load and parse JSON file."""
    print(f"Loading {file_path}...")
    with open(file_path, 'r') as f:
        data = json.load(f)
    print(f"  Loaded {len(data['episodes'])} episodes")
    return data

def extract_examples(data: Dict[str, Any]) -> tuple[Set[str], Set[str]]:
    """
    Extract all support and query examples from the JSON data.
    
    Returns:
        Tuple of (support_examples_set, query_examples_set)
    """
    support_examples = []
    query_examples = []
    episode_ids = []
    
    episodes = data.get('episodes', {})
    
    for episode_id, episode_data in episodes.items():
        episode_ids.append(episode_id)
        # Extract support examples
        episode_samples = episode_data['support'] if 'support' in episode_data else print(f"⚠️  No support examples in episode {episode_id}")
        # Add the query examples
        episode_samples.extend(episode_data.get('query', []) if 'query' in episode_data else print(f"⚠️  No query examples in episode {episode_id}"))
        
        sorted_examples = sorted(episode_samples) if isinstance(episode_samples, list) else []
        support_examples.append('|'.join(sorted_examples))
    
    print(f"  Extracted {len(support_examples)} support examples")
    print(f"  Extracted {len(query_examples)} query examples")
    
    # Convert to sets for overlap analysis
    support_set = set(support_examples)
    query_set = set(query_examples)
    
    print(f"  Unique support examples: {len(support_set)}")
    print(f"  Unique query examples: {len(query_set)}")
    
    return support_set, query_set, episode_ids

def calculate_overlap(set1: Set[str], set2: Set[str], label1: str, label2: str) -> Dict[str, Any]:
    """Calculate overlap statistics between two sets."""
    intersection = set1 & set2
    union = set1 | set2
    
    overlap_stats = {
        f"{label1}_size": len(set1),
        f"{label2}_size": len(set2),
        "intersection_size": len(intersection),
        "union_size": len(union),
        "overlap_percentage": (len(intersection) / len(union)) * 100 if union else 0,
        f"{label1}_only": len(set1 - set2),
        f"{label2}_only": len(set2 - set1),
        "jaccard_similarity": len(intersection) / len(union) if union else 0
    }
    
    return overlap_stats

def analyze_seed_overlap(seed0_file: str, seed2_file: str, dataset_type: str = ""):
    """Main analysis function."""
    print("=" * 80)
    print(f"SEED OVERLAP ANALYSIS{' - ' + dataset_type.upper() if dataset_type else ''}")
    print("=" * 80)
    
    # Load both files
    seed0_data = load_json_file(seed0_file)
    seed2_data = load_json_file(seed2_file)
    
    # Extract examples
    print("\nExtracting examples from seed 0...")
    seed0_support, seed0_query, seed0_episode_ids = extract_examples(seed0_data)
    
    print("\nExtracting examples from seed 2...")
    seed2_support, seed2_query, seed2_episode_ids = extract_examples(seed2_data)
    
    # Calculate overlaps
    print("\n" + "=" * 60)
    print("SUPPORT EXAMPLES OVERLAP")
    print("=" * 60)
    
    support_overlap = calculate_overlap(seed0_support, seed2_support, "seed0_support", "seed2_support")
    
    print(f"Seed 0 support examples: {support_overlap['seed0_support_size']}")
    print(f"Seed 2 support examples: {support_overlap['seed2_support_size']}")
    print(f"Common support examples: {support_overlap['intersection_size']}")
    print(f"Total unique support examples: {support_overlap['union_size']}")
    print(f"Support overlap percentage: {support_overlap['overlap_percentage']:.2f}%")
    print(f"Jaccard similarity (support): {support_overlap['jaccard_similarity']:.4f}")
    print(f"Seed 0 only: {support_overlap['seed0_support_only']}")
    print(f"Seed 2 only: {support_overlap['seed2_support_only']}")
    
    print("\n" + "=" * 60)
    print("QUERY EXAMPLES OVERLAP")
    print("=" * 60)
    
    query_overlap = calculate_overlap(seed0_query, seed2_query, "seed0_query", "seed2_query")
    
    print(f"Seed 0 query examples: {query_overlap['seed0_query_size']}")
    print(f"Seed 2 query examples: {query_overlap['seed2_query_size']}")
    print(f"Common query examples: {query_overlap['intersection_size']}")
    print(f"Total unique query examples: {query_overlap['union_size']}")
    print(f"Query overlap percentage: {query_overlap['overlap_percentage']:.2f}%")
    print(f"Jaccard similarity (query): {query_overlap['jaccard_similarity']:.4f}")
    print(f"Seed 0 only: {query_overlap['seed0_query_only']}")
    print(f"Seed 2 only: {query_overlap['seed2_query_only']}")
    
    # Combined analysis
    print("\n" + "=" * 60)
    print("COMBINED ANALYSIS")
    print("=" * 60)
    
    # Combine support and query for each seed
    seed0_all = seed0_support | seed0_query
    seed2_all = seed2_support | seed2_query
    
    combined_overlap = calculate_overlap(seed0_all, seed2_all, "seed0_all", "seed2_all")
    
    print(f"Seed 0 total examples (support + query): {combined_overlap['seed0_all_size']}")
    print(f"Seed 2 total examples (support + query): {combined_overlap['seed2_all_size']}")
    print(f"Common examples across all: {combined_overlap['intersection_size']}")
    print(f"Total unique examples across all: {combined_overlap['union_size']}")
    print(f"Overall overlap percentage: {combined_overlap['overlap_percentage']:.2f}%")
    print(f"Overall Jaccard similarity: {combined_overlap['jaccard_similarity']:.4f}")
    
    # Cross-category analysis
    print("\n" + "=" * 60)
    print("CROSS-CATEGORY ANALYSIS")
    print("=" * 60)
    
    # Check if seed 0 support appears in seed 2 query and vice versa
    seed0_support_in_seed2_query = seed0_support & seed2_query
    seed2_support_in_seed0_query = seed2_support & seed0_query
    seed0_query_in_seed2_support = seed0_query & seed2_support
    seed2_query_in_seed0_support = seed2_query & seed0_support
    
    print(f"Seed 0 support examples found in seed 2 query: {len(seed0_support_in_seed2_query)}")
    print(f"Seed 2 support examples found in seed 0 query: {len(seed2_support_in_seed0_query)}")
    print(f"Seed 0 query examples found in seed 2 support: {len(seed0_query_in_seed2_support)}")
    print(f"Seed 2 query examples found in seed 0 support: {len(seed2_query_in_seed0_support)}")
    
    # Show some example overlaps if they exist
    if support_overlap['intersection_size'] > 0:
        print(f"\nFirst 5 common support examples:")
        common_support = list(seed0_support & seed2_support)[:5]
        for i, example in enumerate(common_support, 1):
            print(f"  {i}. {example}")
    
    if query_overlap['intersection_size'] > 0:
        print(f"\nFirst 5 common query examples:")
        common_query = list(seed0_query & seed2_query)[:5]
        for i, example in enumerate(common_query, 1):
            print(f"  {i}. {example}")
    
    print("=" * 80)
    
    return {
        "support_overlap": support_overlap,
        "query_overlap": query_overlap,
        "combined_overlap": combined_overlap,
        "cross_category": {
            "seed0_support_in_seed2_query": len(seed0_support_in_seed2_query),
            "seed2_support_in_seed0_query": len(seed2_support_in_seed0_query),
            "seed0_query_in_seed2_support": len(seed0_query_in_seed2_support),
            "seed2_query_in_seed0_support": len(seed2_query_in_seed0_support)
        }
    }

def main():
    """Main function to run the analysis."""
    # Paths to the JSON files
    base_path = "/home/rsaha/projects/dm_alchemy/src/data/held_out_exps_generated_data_enhanced"
    
    # Analyze both train and val datasets
    datasets = ["val"]
    
    for dataset_type in datasets:
        # seed0_file = f"{base_path}/compositional_chemistry_samples_167424_80_unique_stones_{dataset_type}_shop_1_qhop_1_seed_0.json"
        seed0_file = f"{base_path}/compositional_chemistry_samples_167424_80_unique_stones_train_shop_1_qhop_1_single_held_out_color_1_edges_exp_seed_0.json"
        # seed2_file = f"{base_path}/compositional_chemistry_samples_167424_80_unique_stones_{dataset_type}_shop_1_qhop_1_seed_2.json"
        seed2_file = f"{base_path}/compositional_chemistry_samples_167424_80_unique_stones_val_shop_1_qhop_1_single_held_out_color_1_edges_exp_seed_0.json"
        
        # Check if files exist
        if os.path.exists(seed0_file) and os.path.exists(seed2_file):
            results = analyze_seed_overlap(seed0_file, seed2_file, dataset_type)
        else:
            print(f"⚠️  Skipping {dataset_type} dataset - files not found:")
            if not os.path.exists(seed0_file):
                print(f"   Missing: {seed0_file}")
            if not os.path.exists(seed2_file):
                print(f"   Missing: {seed2_file}")
        
        print("\n" + "="*80 + "\n")

if __name__ == "__main__":
    main()
