# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dm_alchemy/protos/episode_info.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dm_alchemy/protos/episode_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$dm_alchemy/protos/episode_info.proto\x12\x08\x64\x65\x65pmind\"u\n\x0b\x45pisodeInfo\x12\r\n\x05\x66rame\x18\x01 \x01(\x05\x12\x14\n\x0ctime_seconds\x18\x02 \x01(\x02\x12\x16\n\x0elength_seconds\x18\x03 \x01(\x02\x12\x14\n\x0c\x65pisode_guid\x18\x04 \x01(\x0c\x12\x13\n\x0brandom_seed\x18\x05 \x01(\x03\x42\x11\xaa\x02\x0e\x44\x65\x65pMind.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dm_alchemy.protos.episode_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016DeepMind.Proto'
  _globals['_EPISODEINFO']._serialized_start=50
  _globals['_EPISODEINFO']._serialized_end=167
# @@protoc_insertion_point(module_scope)
