# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dm_alchemy/protos/events.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dm_alchemy/protos/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from dm_alchemy.protos import episode_info_pb2 as dm__alchemy_dot_protos_dot_episode__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64m_alchemy/protos/events.proto\x12\x11\x64\x65\x65pmind.dmworlds\x1a\x19google/protobuf/any.proto\x1a$dm_alchemy/protos/episode_info.proto\"m\n\nWorldEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x0c\x65pisode_info\x18\x02 \x01(\x0b\x32\x15.deepmind.EpisodeInfo\x12$\n\x06\x64\x65tail\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"A\n\x0bWorldEvents\x12\x32\n\x0bworldevents\x18\x01 \x03(\x0b\x32\x1d.deepmind.dmworlds.WorldEventB\x18\xaa\x02\x15\x44\x65\x65pMind.Proto.Eventsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dm_alchemy.protos.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\025DeepMind.Proto.Events'
  _globals['_WORLDEVENT']._serialized_start=118
  _globals['_WORLDEVENT']._serialized_end=227
  _globals['_WORLDEVENTS']._serialized_start=229
  _globals['_WORLDEVENTS']._serialized_end=294
# @@protoc_insertion_point(module_scope)
